name: URL Monitoring with Persistent Database

on:
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch: # Allow manual triggering
  push:
    branches: [ main ]
    paths:
      - 'urls.csv'
      - '.github/workflows/url-monitor-persistent.yml'

# Security: Explicit permissions for the workflow
permissions:
  contents: read      # To checkout repository
  actions: write      # To upload/download artifacts (database persistence)
  pages: write        # To deploy to GitHub Pages
  id-token: write     # For GitHub Pages deployment
  issues: write       # To create issues on monitoring failures

jobs:
  monitor-urls-persistent:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    # Option 1: Download previous database from artifacts
    - name: Download previous database
      id: download_db
      uses: actions/download-artifact@v4
      with:
        name: monitoring-database
        path: .
      continue-on-error: true  # Continue if no previous database exists
      
    - name: Handle download result
      run: |
        if [ "${{ steps.download_db.outcome }}" = "failure" ]; then
          echo "⚠️ No previous database artifact found (this is normal for first run)"
        else
          echo "✅ Successfully downloaded previous database"
        fi
    
    - name: Check if database exists
      run: |
        if [ -f monitoring.db ]; then
          echo "Found existing database ($(stat -c%s monitoring.db) bytes)"
          echo "DATABASE_EXISTS=true" >> $GITHUB_ENV
        else
          echo "No existing database found, will create new one"
          echo "DATABASE_EXISTS=false" >> $GITHUB_ENV
        fi
    
    - name: Run URL monitoring with persistent database
      run: |
        echo "🚀 Starting URL monitoring..."
        set +e  # Don't exit on errors
        python ci_monitor_persistent.py
        MONITORING_EXIT_CODE=$?
        set -e  # Re-enable exit on errors
        
        echo "MONITORING_STATUS=$MONITORING_EXIT_CODE" >> $GITHUB_ENV
        
        if [ $MONITORING_EXIT_CODE -eq 0 ]; then
          echo "✅ Monitoring completed successfully"
          echo "MONITORING_RESULT=success" >> $GITHUB_ENV
        else
          echo "⚠️ Monitoring completed with issues (exit code: $MONITORING_EXIT_CODE)"
          echo "MONITORING_RESULT=warning" >> $GITHUB_ENV
        fi
        
        # Always continue to next steps regardless of monitoring results
        echo "📦 Proceeding with artifact uploads..."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        DATABASE_EXISTS: ${{ env.DATABASE_EXISTS }}
    
    # Save updated database as artifact for next run
    - name: Upload updated database
      if: always()  # Always upload database, even if monitoring had issues
      uses: actions/upload-artifact@v4
      with:
        name: monitoring-database
        path: monitoring.db
        retention-days: 90  # Keep for 90 days (maximum)
    
    - name: Ensure results directory exists for debugging
      run: |
        echo "📊 Monitoring completed, database updated"
        echo "📁 Database size: $(stat -c%s monitoring.db 2>/dev/null || stat -f%z monitoring.db) bytes"
        echo "✅ Ready for report generation in next job"
    
    - name: Create Issue on Critical Failures
      if: env.MONITORING_STATUS != '0' && env.MONITORING_RESULT == 'warning'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = 'monitoring-results/failures.json';
          
          if (fs.existsSync(path)) {
            const failures = JSON.parse(fs.readFileSync(path, 'utf8'));
            const body = `## URL Monitoring Failures - ${new Date().toISOString()}
            
            The following URLs failed during monitoring:
            
            ${failures.map(f => `- **${f.url}** (${f.group_name}): ${f.error_message || 'Status ' + f.status_code}`).join('\n')}
            
            **Historical Context**: This monitoring run includes ${failures.length > 0 ? 'persistent' : 'no'} database history.
            **Run:** ${context.payload.repository.html_url}/actions/runs/${context.runId}
            `;
            
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `URL Monitoring Failures - ${new Date().toLocaleDateString()}`,
              body: body,
              labels: ['monitoring', 'alert', 'persistent-db']
            });
          }

  generate-historical-report:
    runs-on: ubuntu-latest
    needs: monitor-urls-persistent
    if: always()
    
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    
    # Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
    # However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
    concurrency:
      group: "pages"
      cancel-in-progress: false
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Download updated database
      id: download_db_for_report
      uses: actions/download-artifact@v4
      with:
        name: monitoring-database
        path: .
      continue-on-error: true
    
    - name: Handle database download result  
      run: |
        if [ "${{ steps.download_db_for_report.outcome }}" = "failure" ]; then
          echo "⚠️ No database artifact found (normal for first run)"
        else
          echo "✅ Downloaded database artifact"
        fi
    
    - name: Generate comprehensive historical report
      run: |
        echo "📊 Generating historical report..."
        if [ -f monitoring.db ]; then
          echo "✅ Database found: $(stat -c%s monitoring.db 2>/dev/null || stat -f%z monitoring.db) bytes"
        else
          echo "⚠️ No database found, will create minimal report"
        fi
        
        echo "🚀 Running report generator..."
        python generate_historical_report.py
    
    - name: Check for deployment files
      id: check_files
      run: |
        if [ -d "monitoring-results" ] && [ "$(ls -A monitoring-results)" ]; then
          echo "FILES_EXIST=true" >> $GITHUB_OUTPUT
          echo "✅ Files found for deployment"
        else
          echo "FILES_EXIST=false" >> $GITHUB_OUTPUT
          echo "⚠️ No files found for deployment"
        fi
    
    - name: Setup Pages
      if: github.ref == 'refs/heads/main' && steps.check_files.outputs.FILES_EXIST == 'true'
      uses: actions/configure-pages@v4
    
    - name: Upload artifact for Pages
      if: github.ref == 'refs/heads/main' && steps.check_files.outputs.FILES_EXIST == 'true'
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./monitoring-results
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' && steps.check_files.outputs.FILES_EXIST == 'true'
      id: deployment
      uses: actions/deploy-pages@v4
    
    - name: Send enhanced Slack notification
      if: env.SLACK_WEBHOOK_URL != ''
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        custom_payload: |
          {
            "text": "URL Monitoring Report with Historical Data",
            "attachments": [{
              "color": "${{ job.status == 'success' && 'good' || 'danger' }}",
              "title": "Historical Monitoring Results - ${{ github.run_number }}",
              "title_link": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "fields": [{
                "title": "Status",
                "value": "${{ job.status }}",
                "short": true
              }, {
                "title": "Database",
                "value": "Persistent SQLite",
                "short": true
              }, {
                "title": "Repository",
                "value": "${{ github.repository }}",
                "short": true
              }]
            }]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
